export enum scoreboardTypes {
  PLAYER_1_TOTAL = 'PLAYER_1_TOTAL',
  PLAYER_2_TOTAL = 'PLAYER_2_TOTAL',
  PLAYER_1_TOTAL_LIST = 'PLAYER_1_TOTAL_LIST',
  PLAYER_2_TOTAL_LIST = 'PLAYER_2_TOTAL_LIST',
  TURN = 'TURN',
  SCORE_INPUT_PLACEHOLDER = 'SCORE_INPUT_PLACEHOLDER',
  SCORE_INPUT_VALUE = 'SCORE_INPUT_VALUE',
}
